-- 1. Show all customers
SELECT * FROM customer;

-- 2. Customers with wallet balance > 2000
SELECT name, wallet_balance 
FROM customer
WHERE wallet_balance > 2000;

-- 3. List all charging stations in Bangalore
SELECT name, operator, rating
FROM charging_station
WHERE city = 'Bangalore';

-- 4. Show available charging ports
SELECT port_id, station_id, port_type
FROM charging_port
WHERE status = 'Available';

-- 5. List all completed charging sessions
SELECT session_id, energy_kWh, start_time, end_time
FROM charging_session
WHERE session_status = 'Completed';


-- =========================
-- INTERMEDIATE QUERIES
-- =========================

-- 6. Customer with their vehicle details
SELECT c.name, v.brand, v.model
FROM customer c
JOIN vehicle v ON c.customer_id = v.customer_id;

-- 7. Charging session with station name
SELECT s.session_id, cs.name AS station_name, s.energy_kWh
FROM charging_session s
JOIN charging_port p ON s.port_id = p.port_id
JOIN charging_station cs ON p.station_id = cs.station_id;

-- 8. Total number of sessions per customer
SELECT c.name, COUNT(s.session_id) AS total_sessions
FROM customer c
LEFT JOIN charging_session s ON c.customer_id = s.customer_id
GROUP BY c.name;

-- 9. Total energy consumed by each customer
SELECT c.name, SUM(s.energy_kWh) AS total_energy
FROM customer c
JOIN charging_session s ON c.customer_id = s.customer_id
GROUP BY c.name;

-- 10. Average rating of each charging station
SELECT cs.name, AVG(f.rating) AS avg_rating
FROM charging_station cs
JOIN Feedback f ON cs.station_id = f.station_id
GROUP BY cs.name;

-- 11. Top 3 customers by total spending
SELECT c.name, SUM(b.total_amount) AS total_spent
FROM customer c
JOIN charging_session s ON c.customer_id = s.customer_id
JOIN billing b ON s.session_id = b.session_id
GROUP BY c.name
ORDER BY total_spent DESC
LIMIT 3;

-- 12. Find stations with more than 2 charging ports
SELECT cs.name, COUNT(p.port_id) AS total_ports
FROM charging_station cs
JOIN charging_port p ON cs.station_id = p.station_id
GROUP BY cs.name
HAVING COUNT(p.port_id) > 2;

-- 13. Customers who used more than 20 kWh total energy
SELECT c.name, SUM(s.energy_kWh) AS total_energy
FROM customer c
JOIN charging_session s ON c.customer_id = s.customer_id
GROUP BY c.name
HAVING total_energy > 20;

-- 14. Revenue generated by each charging station
SELECT cs.name, SUM(b.total_amount) AS total_revenue
FROM charging_station cs
JOIN charging_port p ON cs.station_id = p.station_id
JOIN charging_session s ON p.port_id = s.port_id
JOIN billing b ON s.session_id = b.session_id
GROUP BY cs.name
ORDER BY total_revenue DESC;

-- 15. Most used charging port type
SELECT p.port_type, COUNT(*) AS usage_count
FROM charging_port p
JOIN charging_session s ON p.port_id = s.port_id
GROUP BY p.port_type
ORDER BY usage_count DESC
LIMIT 1;

-- 16. Customers who have not given feedback
SELECT c.name
FROM customer c
LEFT JOIN Feedback f ON c.customer_id = f.customer_id
WHERE f.customer_id IS NULL;

-- project end